---
name: "Build & publish docker image"

on:
  push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-docker-image:
    name: Build & publish docker image to the GitHub container registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Login to the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build '.#docker'
      - run: docker load <result
      - run: docker tag syslog-utils:latest ${{ env.REGISTRY }}/${IMAGE_NAME}:latest
      - run: docker push ${{ env.REGISTRY }}/${IMAGE_NAME}:latest
