---
name: "Publish Release"

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-release-binaries:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Create the output directory
        run: mkdir output

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Login to the container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build release binaries
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build '.#static'

      - name: Copy release binaries to output directory
        run: cp result/bin/syslog-client result/bin/syslog-server output

      - name: Build release docker image
        run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build '.#docker'

      - name: Copy docker image to output directory
        run: cp result output/docker-image

      - run: docker load <result
      - run: docker tag syslog-utils:latest ${{ env.REGISTRY }}/${IMAGE_NAME}:latest
      - run: docker tag syslog-utils:latest ${{ env.REGISTRY }}/${IMAGE_NAME}:${{ github.ref_name }}
      - run: docker push ${{ env.REGISTRY }}/${IMAGE_NAME}:${{ github.ref_name }}

      - name: Create the release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            output/syslog-client
            output/syslog-server
            output/docker-image
