---
name: "Build & publish release binaries"
on:
  push:
    tags:
      - 'v*'


jobs:
  publish_binaries:
    name: Build & publish release binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix --extra-experimental-features nix-command --extra-experimental-features flakes build '.#static'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            result/bin/syslog-client
            result/bin/syslog-server

